config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/consumer', to: 'static_pages#consumer'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: valid_email_regex },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def consumer; end

  def contact; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
  <footer class="footer">
<small>
The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About",
about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li> <%= link_to "Consumer", consumer_path %> </li>
<li> <%= link_to "Home", root_path %> </li>

<li><a href="https://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>
  </footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top bg-dark">
    <div class="container d-flex">
     <%= link_to 'sample app', '#', id: 'logo' %>
    <nav>
  <ul class="navbar-nav d-flex flex-row">
  <li class="nav-item mx-2"><%= link_to 'Home', root_path %></li>
  <li class="nav-item mx-2"> <%= link_to 'Help', help_path %> </li>
  <li class="nav-item mx-2"> <%= link_to 'Log in',    '#' %> </li>
  </ul>
  </nav>
  </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails tutorial</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header'%>
  <div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  <%= yield %>
  <%= render 'layouts/footer'%>
  <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="danger">
      The form contains <%= pluralize(@user.errors.count, 'error')%>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1> This is a test </h1>

app/views/static_pages/consumer.html.erb
<% provide(:title, 'Consumer') %>
<h1> This is a test </h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1> This is a test </h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2>This is the home page for the <a href="#">Ruby on Rails Tutorial</a> sample application</h2>
    <%= link_to 'Sign up now!', signup_path, class: 'btn btn-dark'%>
</div>
<%= link_to image_tag('rails.svg', alt: 'rails logo', width: '299'), 
"https://rubyonrails.org/ "%>
<%= link_to image_tag('cat.png', width: '450'), 'https://www.reddit.com'%>

app/views/users/new.html.erb
% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_with(model: @user, local: true) do |f| %>
<%= render 'shared/error_messages'%>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.email_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
</div>